FROM node:24-alpine
ENV NODE_ENV=development
WORKDIR /app

COPY package*.json package-lock.json* ./
RUN --mount=type=cache,target=/root/.npm npm install
COPY . .
EXPOSE 4200
CMD ["npm", "start", "--", "--host=0.0.0.0"]